//! MemoryProcessor service
//!
//! Responsible for LLM-driven event-to-memory extraction and query enhancement.
//! Memory metadata is generated directly against the active system profile schema.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::sync::Arc;
use tracing::{debug, info, warn};

use crate::domain::InferenceType;
use crate::llm::{ChatRequest, LlmError, LlmProvider};

/// Error type for memory processing operations
#[derive(Debug, thiserror::Error)]
pub enum ProcessingError {
    /// LLM provider error
    #[error("LLM error: {0}")]
    LlmError(#[from] LlmError),

    /// Failed to parse LLM response
    #[error("Failed to parse LLM response: {0}")]
    ParseError(String),

    /// Event content too short for processing
    #[error("Event content too short: minimum {min} characters required")]
    EventContentTooShort { min: usize },

    /// No valid memories could be extracted from event
    #[error("No valid memories could be extracted from event")]
    NoMemoriesExtracted,

    /// Query enhancement failed
    #[error("Query enhancement failed: {0}")]
    QueryEnhancementFailed(String),
}

/// Structured memory extracted from an event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtractedMemory {
    /// The extracted memory content
    pub content: String,
    /// Structured metadata payload following the current profile schema
    pub metadata: Value,
    /// Schema version attached to the metadata payload
    pub schema_version: i32,
    /// Importance score (0.0 - 1.0)
    pub importance: f32,
    /// Confidence score for this extraction (0.0 - 1.0)
    pub confidence: f32,
    /// Type of inference made (fact, preference, pattern, rule)
    pub inference_type: InferenceType,
    /// Confidence of the inference decision
    pub inference_confidence: f32,
    /// Reasoning explaining why this memory was extracted
    pub inference_reasoning: String,
}

/// Request for extracting memories from an event.
#[derive(Debug, Clone)]
pub struct ExtractFromEventRequest {
    /// Event content (can be any form: click description, conversation history, operation log, etc.)
    pub content: String,
    /// Optional context to help LLM better understand the event
    pub context: Option<String>,
    /// System-specific extraction prompt generated by the profile
    pub extraction_prompt: String,
    /// Metadata schema contract for the current profile
    pub metadata_schema: Value,
    /// Schema generation prompt returned by the profile
    pub schema_generation_prompt: Option<String>,
    /// Active schema version
    pub schema_version: i32,
}

impl ExtractFromEventRequest {
    /// Create a new extract from event request
    pub fn new(
        content: impl Into<String>,
        extraction_prompt: impl Into<String>,
        metadata_schema: Value,
        schema_generation_prompt: Option<String>,
        schema_version: i32,
    ) -> Self {
        Self {
            content: content.into(),
            context: None,
            extraction_prompt: extraction_prompt.into(),
            metadata_schema,
            schema_generation_prompt,
            schema_version,
        }
    }

    /// Create a new extract from event request with context
    pub fn with_context(
        content: impl Into<String>,
        context: impl Into<String>,
        extraction_prompt: impl Into<String>,
        metadata_schema: Value,
        schema_generation_prompt: Option<String>,
        schema_version: i32,
    ) -> Self {
        Self {
            content: content.into(),
            context: Some(context.into()),
            extraction_prompt: extraction_prompt.into(),
            metadata_schema,
            schema_generation_prompt,
            schema_version,
        }
    }
}

/// Result of extracting memories from an event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtractFromEventResult {
    /// Event summary (LLM-generated understanding of the event)
    pub event_summary: String,
    /// List of extracted memories
    pub extracted_memories: Vec<ExtractedMemory>,
    /// Overall processing confidence score (0.0 - 1.0)
    pub confidence: f32,
}

/// Enhanced query result containing both original and enhanced queries.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnhancedQuery {
    /// The original query provided by the user
    pub original_query: String,
    /// The enhanced query with semantic expansions
    pub enhanced_query: String,
}

/// Prompt template for summarizing long conversations
const SUMMARIZE_PROMPT: &str = r#"你是一个对话摘要助手。请对以下长对话/事件内容进行摘要，保留关键信息：

1. 保留关键事实、偏好、决策和约束
2. 删除重复内容、寒暄和无关信息
3. 保留时间、对象、状态变化和结论

原始内容：
{content}

请直接返回摘要内容，不要添加解释。"#;

/// Prompt template for query enhancement
const ENHANCE_QUERY_PROMPT: &str = r#"你是一个查询增强助手。请对以下查询进行语义扩展，添加同义词和相关术语以提高检索效果。

原始查询：
{query}
{context_section}

请严格按照以下JSON格式返回结果：
```json
{
  "original_query": "原始查询",
  "enhanced_query": "扩展后的查询（包含原始查询和扩展词）"
}
```"#;

/// Minimum content length for event processing
const MIN_EVENT_CONTENT_LENGTH: usize = 10;

/// Content length threshold for summarization (approximately 2000 tokens)
const SUMMARIZE_THRESHOLD: usize = 4000;

/// MemoryProcessor service for LLM-driven memory processing
pub struct MemoryProcessor {
    /// LLM provider for processing
    llm_provider: Arc<dyn LlmProvider>,
}

impl MemoryProcessor {
    /// Create a new MemoryProcessor with the given LLM provider
    pub fn new(llm_provider: Arc<dyn LlmProvider>) -> Self {
        Self { llm_provider }
    }

    /// Check if content needs summarization before processing.
    pub fn needs_summary(&self, content: &str) -> bool {
        content.len() > SUMMARIZE_THRESHOLD
    }

    /// Summarize long conversation/event content.
    pub async fn summarize_conversation(&self, content: &str) -> Result<String, ProcessingError> {
        debug!(content_len = content.len(), "Summarizing long conversation");

        let prompt = SUMMARIZE_PROMPT.replace("{content}", content);
        let chat_request = ChatRequest::new(prompt).with_temperature(0.3);
        let response = self.llm_provider.chat(chat_request).await?;
        let summary = response.content.trim().to_string();

        info!(
            original_len = content.len(),
            summary_len = summary.len(),
            "Conversation summarized"
        );

        Ok(summary)
    }

    /// Build the extraction prompt with profile-specific schema instructions.
    fn build_extraction_prompt(&self, request: &ExtractFromEventRequest, content: &str) -> String {
        let context_section = match &request.context {
            Some(ctx) => format!("\n补充上下文：\n{}", ctx),
            None => String::new(),
        };

        let schema_generation_prompt = request
            .schema_generation_prompt
            .as_deref()
            .unwrap_or("请严格按照 metadata_schema 输出 metadata，不要杜撰未知字段。");

        format!(
            r#"{extraction_prompt}

你现在要把事件转换为可落库的 memory 提案。请严格基于下列 schema 和生成约束输出。

当前 schema_version: {schema_version}

metadata_schema:
```json
{metadata_schema}
```

metadata 生成约束:
{schema_generation_prompt}

事件内容:
{content}
{context_section}

请严格按照以下 JSON 返回，不要输出额外解释：
```json
{{
  "event_summary": "对事件的简要理解",
  "extracted_memories": [
    {{
      "content": "提取的记忆内容",
      "inference_type": "fact|preference|pattern|rule",
      "confidence": 0.9,
      "metadata": {{}},
      "importance": 0.7,
      "reasoning": "为什么提取这条记忆"
    }}
  ],
  "confidence": 0.85
}}
```

要求：
- metadata 必须是 JSON object，并遵守 metadata_schema
- 只要事件表达了与业务领域有关的偏好、反偏好、预算/资源能力、约束、决策阶段、目标或状态变化，就应提取为记忆
- 如果新事件改变、放宽、强化或推翻了补充上下文中的历史记忆，应提取一条新的当前状态记忆；不要因为没有具体商品/房源/对象明细就返回空数组
- 对推荐、选购、决策类系统，价格承受度、预算压力、支付能力、生活质量目标、环境改善意愿都属于高价值记忆信号
- 如果无法提取有效记忆，返回空数组
- 不要返回 category、tags 这类旧字段，统一放进 metadata
- fact 一般用于明确事实，preference/pattern/rule 用于推断或规则归纳"#,
            extraction_prompt = request.extraction_prompt,
            schema_version = request.schema_version,
            metadata_schema = request.metadata_schema,
            schema_generation_prompt = schema_generation_prompt,
            content = content,
            context_section = context_section,
        )
    }

    /// Extract memories from an event
    pub async fn extract_from_event(
        &self,
        request: ExtractFromEventRequest,
    ) -> Result<ExtractFromEventResult, ProcessingError> {
        debug!(
            content_len = request.content.len(),
            has_context = request.context.is_some(),
            schema_version = request.schema_version,
            "Extracting memories from event"
        );

        if request.content.trim().len() < MIN_EVENT_CONTENT_LENGTH {
            return Err(ProcessingError::EventContentTooShort {
                min: MIN_EVENT_CONTENT_LENGTH,
            });
        }

        let content = if self.needs_summary(&request.content) {
            self.summarize_conversation(&request.content).await?
        } else {
            request.content.clone()
        };

        let prompt = self.build_extraction_prompt(&request, &content);
        let chat_request = ChatRequest::new(prompt)
            .with_temperature(0.3)
            .with_json_response();

        let response = self.llm_provider.chat(chat_request).await?;
        let result = Self::parse_extraction_response(&response.content, request.schema_version)?;

        info!(
            memory_count = result.extracted_memories.len(),
            confidence = result.confidence,
            "Memories extracted from event"
        );

        Ok(result)
    }

    /// Parse the extraction response from LLM
    fn parse_extraction_response(
        response: &str,
        schema_version: i32,
    ) -> Result<ExtractFromEventResult, ProcessingError> {
        let json_str = Self::extract_json(response);

        let parsed: Value = serde_json::from_str(&json_str).map_err(|e| {
            warn!(
                response = %response,
                error = %e,
                "Failed to parse extraction response"
            );
            ProcessingError::ParseError(format!("Invalid JSON: {}", e))
        })?;

        let event_summary = parsed["event_summary"]
            .as_str()
            .unwrap_or("")
            .trim()
            .to_string();

        let confidence = parsed["confidence"]
            .as_f64()
            .map(|v| v as f32)
            .unwrap_or(0.5)
            .clamp(0.0, 1.0);

        let extracted_memories =
            Self::parse_extracted_memories(&parsed["extracted_memories"], schema_version)?;

        Ok(ExtractFromEventResult {
            event_summary,
            extracted_memories,
            confidence,
        })
    }

    /// Parse extracted memories from JSON array
    fn parse_extracted_memories(
        value: &Value,
        schema_version: i32,
    ) -> Result<Vec<ExtractedMemory>, ProcessingError> {
        let arr = match value.as_array() {
            Some(arr) => arr,
            None => return Ok(Vec::new()),
        };

        let mut memories = Vec::new();

        for item in arr {
            let content = item["content"].as_str().unwrap_or("").trim().to_string();
            if content.is_empty() {
                continue;
            }

            let metadata = item["metadata"].clone();
            if !metadata.is_object() {
                continue;
            }

            let inference_type =
                Self::parse_inference_type(item["inference_type"].as_str().unwrap_or("fact"));

            let confidence = item["confidence"]
                .as_f64()
                .map(|v| (v as f32).clamp(0.0, 1.0))
                .unwrap_or(0.5);

            let importance = item["importance"]
                .as_f64()
                .map(|v| (v as f32).clamp(0.0, 1.0))
                .unwrap_or(0.5);

            let reasoning = item["reasoning"].as_str().unwrap_or("").trim().to_string();

            memories.push(ExtractedMemory {
                content,
                metadata,
                schema_version,
                importance,
                confidence,
                inference_type,
                inference_confidence: confidence,
                inference_reasoning: reasoning,
            });
        }

        Ok(memories)
    }

    /// Extract JSON from response (handles markdown code blocks)
    fn extract_json(response: &str) -> String {
        let response = response.trim();

        if let Some(start) = response.find("```json") {
            if let Some(end) = response[start..]
                .find("```\n")
                .or(response[start..].rfind("```"))
            {
                let json_start = start + 7;
                let json_end = start + end;
                if json_start < json_end {
                    return response[json_start..json_end].trim().to_string();
                }
            }
        }

        if let Some(start) = response.find("```") {
            let after_start = start + 3;
            if let Some(end) = response[after_start..].find("```") {
                let content = &response[after_start..after_start + end];
                let json_content = content
                    .lines()
                    .skip_while(|line| !line.trim().starts_with('{'))
                    .collect::<Vec<_>>()
                    .join("\n");
                if !json_content.is_empty() {
                    return json_content.trim().to_string();
                }
            }
        }

        if let Some(start) = response.find('{') {
            if let Some(end) = response.rfind('}') {
                if start < end {
                    return response[start..=end].to_string();
                }
            }
        }

        response.to_string()
    }

    /// Parse inference type from string
    fn parse_inference_type(s: &str) -> InferenceType {
        match s.to_lowercase().as_str() {
            "fact" => InferenceType::Fact,
            "preference" => InferenceType::Preference,
            "pattern" => InferenceType::Pattern,
            "rule" => InferenceType::Rule,
            _ => InferenceType::Fact,
        }
    }

    /// Enhance a query with semantic synonyms
    pub async fn enhance_query(
        &self,
        query: &str,
        context: Option<&str>,
    ) -> Result<EnhancedQuery, ProcessingError> {
        debug!(
            query_len = query.len(),
            has_context = context.is_some(),
            "Enhancing query"
        );

        let context_section = match context {
            Some(ctx) => format!("\n上下文信息：\n{}", ctx),
            None => String::new(),
        };

        let prompt = ENHANCE_QUERY_PROMPT
            .replace("{query}", query)
            .replace("{context_section}", &context_section);

        let chat_request = ChatRequest::new(prompt)
            .with_temperature(0.3)
            .with_json_response();

        let response = self
            .llm_provider
            .chat(chat_request)
            .await
            .map_err(|e| ProcessingError::QueryEnhancementFailed(e.to_string()))?;

        let result = Self::parse_enhanced_query_response(&response.content, query)?;

        info!(
            original_len = query.len(),
            enhanced_len = result.enhanced_query.len(),
            "Query enhanced"
        );

        Ok(result)
    }

    /// Parse enhanced query response from LLM
    fn parse_enhanced_query_response(
        response: &str,
        original_query: &str,
    ) -> Result<EnhancedQuery, ProcessingError> {
        let json_str = Self::extract_json(response);

        let parsed: Value = serde_json::from_str(&json_str).map_err(|e| {
            warn!(
                response = %response,
                error = %e,
                "Failed to parse enhanced query response"
            );
            ProcessingError::QueryEnhancementFailed(format!("Invalid JSON: {}", e))
        })?;

        let enhanced_query = parsed["enhanced_query"]
            .as_str()
            .unwrap_or(original_query)
            .trim()
            .to_string();

        Ok(EnhancedQuery {
            original_query: original_query.to_string(),
            enhanced_query,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_from_event_request_new() {
        let request = ExtractFromEventRequest::new(
            "Test event content",
            "extract prompt",
            serde_json::json!({"entity_types": {}}),
            Some("schema prompt".to_string()),
            3,
        );
        assert_eq!(request.content, "Test event content");
        assert!(request.context.is_none());
        assert_eq!(request.schema_version, 3);
    }

    #[test]
    fn test_extract_from_event_request_with_context() {
        let request = ExtractFromEventRequest::with_context(
            "Test event",
            "Some context",
            "extract prompt",
            serde_json::json!({"entity_types": {}}),
            Some("schema prompt".to_string()),
            2,
        );
        assert_eq!(request.content, "Test event");
        assert_eq!(request.context, Some("Some context".to_string()));
        assert_eq!(request.schema_version, 2);
    }

    #[test]
    fn test_extract_json_from_code_block() {
        let response = r#"```json
{
  "event_summary": "test content",
  "extracted_memories": []
}
```"#;
        let json = MemoryProcessor::extract_json(response);
        assert!(json.contains("event_summary"));
    }

    #[test]
    fn test_extract_json_raw() {
        let response = r#"{"event_summary": "test", "extracted_memories": []}"#;
        let json = MemoryProcessor::extract_json(response);
        assert_eq!(json, response);
    }

    #[test]
    fn test_needs_summary_short_content() {
        use crate::llm::{LlmProviderConfig, LlmProviderType, LocalLlmProvider};

        let config = LlmProviderConfig {
            name: "test".to_string(),
            provider_type: LlmProviderType::Local,
            endpoint: "http://localhost:11434".to_string(),
            api_key: Some("test-key".to_string()),
            model: "test".to_string(),
            enabled: true,
        };
        let provider = Arc::new(LocalLlmProvider::new(config).unwrap());
        let processor = MemoryProcessor::new(provider);

        assert!(!processor.needs_summary(&"a".repeat(100)));
        assert!(!processor.needs_summary(&"a".repeat(4000)));
        assert!(processor.needs_summary(&"a".repeat(4001)));
    }

    #[test]
    fn test_parse_inference_type() {
        assert_eq!(
            MemoryProcessor::parse_inference_type("fact"),
            InferenceType::Fact
        );
        assert_eq!(
            MemoryProcessor::parse_inference_type("preference"),
            InferenceType::Preference
        );
        assert_eq!(
            MemoryProcessor::parse_inference_type("pattern"),
            InferenceType::Pattern
        );
        assert_eq!(
            MemoryProcessor::parse_inference_type("rule"),
            InferenceType::Rule
        );
        assert_eq!(
            MemoryProcessor::parse_inference_type("unknown"),
            InferenceType::Fact
        );
    }

    #[test]
    fn test_parse_extraction_response() {
        let response = r#"{
            "event_summary": "用户表达了对深色主题的偏好",
            "extracted_memories": [
                {
                    "content": "用户喜欢深色主题",
                    "inference_type": "preference",
                    "confidence": 0.8,
                    "metadata": {
                        "memory_type": "ui_preference",
                        "theme": "dark"
                    },
                    "importance": 0.7,
                    "reasoning": "用户明确表示喜欢深色主题"
                }
            ],
            "confidence": 0.85
        }"#;

        let result = MemoryProcessor::parse_extraction_response(response, 4).unwrap();

        assert_eq!(result.event_summary, "用户表达了对深色主题的偏好");
        assert_eq!(result.confidence, 0.85);
        assert_eq!(result.extracted_memories.len(), 1);

        let memory = &result.extracted_memories[0];
        assert_eq!(memory.content, "用户喜欢深色主题");
        assert_eq!(memory.inference_type, InferenceType::Preference);
        assert!((memory.confidence - 0.8).abs() < 0.01);
        assert_eq!(memory.metadata["memory_type"], "ui_preference");
        assert_eq!(memory.schema_version, 4);
        assert!((memory.importance - 0.7).abs() < 0.01);
        assert_eq!(memory.inference_reasoning, "用户明确表示喜欢深色主题");
    }

    #[test]
    fn test_parse_extraction_response_with_code_block() {
        let response = r#"```json
{
    "event_summary": "测试事件",
    "extracted_memories": [],
    "confidence": 0.5
}
```"#;

        let result = MemoryProcessor::parse_extraction_response(response, 1).unwrap();

        assert_eq!(result.event_summary, "测试事件");
        assert!(result.extracted_memories.is_empty());
        assert!((result.confidence - 0.5).abs() < 0.01);
    }

    #[test]
    fn test_parse_extraction_response_multiple_memories() {
        let response = r#"{
            "event_summary": "用户讨论了工作习惯",
            "extracted_memories": [
                {
                    "content": "用户每天早上9点开始工作",
                    "inference_type": "fact",
                    "confidence": 0.95,
                    "metadata": {"memory_type": "work_schedule", "start_time": "09:00"},
                    "importance": 0.6,
                    "reasoning": "用户明确提到工作时间"
                },
                {
                    "content": "用户喜欢在安静环境中工作",
                    "inference_type": "preference",
                    "confidence": 0.7,
                    "metadata": {"memory_type": "work_preference", "environment": "quiet"},
                    "importance": 0.5,
                    "reasoning": "从对话中推断"
                }
            ],
            "confidence": 0.8
        }"#;

        let result = MemoryProcessor::parse_extraction_response(response, 1).unwrap();

        assert_eq!(result.extracted_memories.len(), 2);
        assert_eq!(
            result.extracted_memories[0].inference_type,
            InferenceType::Fact
        );
        assert_eq!(
            result.extracted_memories[1].inference_type,
            InferenceType::Preference
        );
    }

    #[test]
    fn test_parse_enhanced_query_response() {
        let response = r#"{
            "original_query": "深色主题",
            "enhanced_query": "深色主题 暗色模式 dark theme 夜间模式"
        }"#;

        let result = MemoryProcessor::parse_enhanced_query_response(response, "深色主题").unwrap();

        assert_eq!(result.original_query, "深色主题");
        assert_eq!(
            result.enhanced_query,
            "深色主题 暗色模式 dark theme 夜间模式"
        );
    }

    #[test]
    fn test_parse_enhanced_query_response_fallback() {
        let response = r#"{"invalid": "response"}"#;

        let result = MemoryProcessor::parse_enhanced_query_response(response, "original").unwrap();

        assert_eq!(result.original_query, "original");
        assert_eq!(result.enhanced_query, "original");
    }

    #[test]
    fn test_prompt_templates_contain_placeholders() {
        assert!(SUMMARIZE_PROMPT.contains("{content}"));
        assert!(ENHANCE_QUERY_PROMPT.contains("{query}"));
        assert!(ENHANCE_QUERY_PROMPT.contains("{context_section}"));
    }

    #[test]
    fn test_parse_extracted_memories_clamps_confidence() {
        let json = serde_json::json!([
            {
                "content": "test",
                "inference_type": "fact",
                "confidence": 1.5,
                "metadata": {},
                "importance": -0.5,
                "reasoning": "test"
            }
        ]);

        let memories = MemoryProcessor::parse_extracted_memories(&json, 2).unwrap();

        assert_eq!(memories.len(), 1);
        assert!((memories[0].confidence - 1.0).abs() < 0.01);
        assert!((memories[0].importance - 0.0).abs() < 0.01);
        assert_eq!(memories[0].schema_version, 2);
    }

    #[test]
    fn test_parse_extracted_memories_filters_invalid_entries() {
        let json = serde_json::json!([
            {
                "content": "",
                "inference_type": "fact",
                "confidence": 0.9,
                "metadata": {},
                "importance": 0.5,
                "reasoning": "test"
            },
            {
                "content": "valid content",
                "inference_type": "fact",
                "confidence": 0.9,
                "metadata": {"memory_type": "valid"},
                "importance": 0.5,
                "reasoning": "test"
            },
            {
                "content": "bad metadata",
                "inference_type": "fact",
                "confidence": 0.9,
                "metadata": "not-an-object",
                "importance": 0.5,
                "reasoning": "test"
            }
        ]);

        let memories = MemoryProcessor::parse_extracted_memories(&json, 1).unwrap();

        assert_eq!(memories.len(), 1);
        assert_eq!(memories[0].content, "valid content");
    }
}
